### ISSUE TITLE
Multiple pages support?

### ISSUE THREAD

**Issue by MBurchard** [lhapaipai/vite-plugin-symfony#14]
Hello Hugues,
thank you for this helpful plugin.
Using it for my Symfony project with only one TWIG Template reachable under one URL works fine.

I have a website in mind that contains at least one more page.
- the normal user frontend
- the admin frontend
I don't want to mix both in one Vue.js app but rather in separate pages.

Is this possible with the current version of the plugin?
Would you add an example at the README.md?

**Comment by MBurchard** [comment]
I withdraw the stupid question.
Since this is very simple with Vite, and the plug-in also implements it 1:1, you don't have to do much for this solution.

If anyone is interested in how to do it... https://github.com/burchard-it/BIT-Webspace-Vue/pull/5

**Comment by lhapaipai** [comment]
hi @MBurchard,
I suggest you to use `parent()` in your inherited templates.
```twig
{% extends 'base.html.twig' %}

{% block title %}BIT Webspace Vue Admin Frontend{% endblock %}

{% block stylesheets %}
  {{ parent() }}
  {{ vite_entry_link_tags('admin') }}
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ vite_entry_script_tags('admin') }}
{% endblock %}

{% block body %}
  <div id="app"></div>
{% endblock %}
```

**Comment by MBurchard** [comment]
Hi @lhapaipai, thank you  :)
