### ISSUE TITLE
TypeError: symfonyPlugin is not a function

### ISSUE THREAD

**Issue by dlt98** [lhapaipai/vite-plugin-symfony#15]
When I try to add the plugin to my `vite.config.ts` in the plugins array I get the error when starting up my vite server, saying that it is not a function.
I am unsure what could be causing this, potentially the wrong type being returned from the function. I tried calling it without the function call but it doesn't seem to work. 

When I compare it to the react plugin I am using the `react()` call returns the type `PluginOption[]` while the symfony plugin returns `Plugin_2`. I am guessing that is the issue.

My vite.config.ts file is below

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import symfonyPlugin from "vite-plugin-symfony";

export default defineConfig({
  plugins: [react(), symfonyPlugin()],
});
```

**Comment by lhapaipai** [comment]
can you look at [https://github.com/lhapaipai/vite-bundle/issues/41](https://github.com/lhapaipai/vite-bundle/issues/41)
