### ISSUE TITLE
Build fail with powershell

### ISSUE THREAD

**Issue by doloryn** [lhapaipai/vite-plugin-symfony#24]
Hello,

When I try to build in a powershell environnement I have this error : 

`unable to map generatedFile`

https://github.com/lhapaipai/vite-plugin-symfony/blob/b6f26a884e1ec0136aca1ac1ca22431ab0954132/src/entryPointsHelper.ts#L36

It's try to find the key : `assets\app.js` in this data : 

```
getBuildEntryPoints {
  'assets/app.css': 'assets/app-a7fd866f.css',
  '_assets/app-a7fd866f.css': 'assets/app-a7fd866f.css',
  'assets/app.js': 'assets/app-b77cc01a.js'
}
```

The difference is the slash and the backslash.

https://github.com/lhapaipai/vite-plugin-symfony/blob/b6f26a884e1ec0136aca1ac1ca22431ab0954132/src/utils.ts#L181

When I modifiy the code as below (as suggested here : https://stackoverflow.com/a/70560464), all seems to work :

`const entryRelativePath = (0, import_path2.relative)(config.root, entryAbsolutePath);`

by 

```
let entryRelativePath = (0, import_path2.relative)(config.root, entryAbsolutePath);
entryRelativePath= entryRelativePath.split("\\").join('/');
```

D:/xxx/assets/app.js -> assets\app.js -> assets/app.js

**Comment by lhapaipai** [comment]
I think I fix this issue, can you confirm because I'm not a powershell user :-)

**Comment by Rhilip** [comment]
I alose meet This bug. Now it fixed when I find this issue and manually upgrade the `vite-plugin-symfony`.
Can you upgrade the default the version of `vite-plugin-symfony` in install template? It might help a lot.

https://github.com/lhapaipai/vite-bundle/blob/0ef2fe988788a42db2f38f14b18feb2a54f5ae10/install/package.json#L10
