### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by FluffyDiscord** [lhapaipai/vite-plugin-symfony#25]
## Add option to exclude directories from watch

Right now this plugin starts folder watch on the project root.

**I need to test project with a lot of files** and the watcher dies, because there are too many opened handlers.

**Increasing `fs.inotify.max_user_watches` is not an option**, as I have millions of files and opening millions of file handlers is something I would like to avoid. If excluding is too much work, then change it to included only.

**We only need to watch `assets`, `templates` and probably `src` too, which would be sane defaults and user could change that.**

![image](https://github.com/lhapaipai/vite-plugin-symfony/assets/10332247/27933911-02be-40d3-82a4-03228c35d85c)

**Comment by lhapaipai** [comment]
you're right.
I don't know if it's a good idea to add an option to the plugin because it's not him who observes the files but chokidar, might as well configure chokidar directly?
https://github.com/paulmillr/chokidar#api

you can see in vite source code:
```ts
// extra/vite/packages/vite/src/node/server/index.ts
  const watcher = chokidar.watch(
    // config file dependencies and env file might be outside of root
    [root, ...config.configFileDependencies, config.envDir],
    resolvedWatchOptions,
  ) as FSWatcher
```


```ts
// extra/vite/packages/vite/src/node/watch.ts
export function resolveChokidarOptions(
  config: ResolvedConfig,
  options: WatchOptions | undefined,
): WatchOptions {
  const { ignored = [], ...otherOptions } = options ?? {}

  const resolvedWatchOptions: WatchOptions = {
    ignored: [
      '**/.git/**',
      '**/node_modules/**',
      '**/test-results/**', // Playwright
      glob.escapePath(config.cacheDir) + '/**',
      ...(Array.isArray(ignored) ? ignored : [ignored]),
    ],
    ignoreInitial: true,
    ignorePermissionErrors: true,
    ...otherOptions,
  }

  return resolvedWatchOptions
}
```

Maybe you can add this to you `vite.config.js`

```js
import { defineConfig } from 'vite'
import { dirname } from 'path';
import { fileURLToPath } from 'url';

export default defineConfig({
  server: {
    watch: { /* File system watcher options to pass on to chokidar. */
      ignored: [
        '**/vendor/**',
        /* or */
        dirname(fileURLToPath(import.meta.url)) + '/vendor/**',
        /* or */
        'anything you want ?'
      ]
    }
  },
```

**Comment by lhapaipai** [comment]
hi @FluffyDiscord,
I added vendor directory to default ignored directory for chokidar file system watcher.

**Comment by FluffyDiscord** [comment]
hi @lhapaipai  would you consider adding also `node_modules` and `public` ? I think both of them are also reasonable, since you don't have to watch javascript packages (if you need them, you import them in JS/CSS anyway) and public folder, which is mostly used for assets storage.

**Comment by lhapaipai** [comment]
you convinced me so I added vendor, var and public to ignored directory.

after investigation it seems that relative path for file watcher like `config.cacheDir` in `extra/vite/packages/vite/src/node/watch.ts` isn't working. I think it's ok with this in v4.3.1.

if you want to review : 
https://github.com/lhapaipai/vite-plugin-symfony/blob/86c68b66fe8133d916c3330154248cd77a82b269/src/index.ts#L73

**Comment by FluffyDiscord** [comment]
shouldn't this line be `userConfig.server?.watch?.ignored` instead of `[]` ? If user has its own config, this plugin shouldn't overwrite it, either add its own or not at all

https://github.com/lhapaipai/vite-plugin-symfony/blob/86c68b66fe8133d916c3330154248cd77a82b269/src/index.ts#L72

**Comment by lhapaipai** [comment]
paths are not replaced but appended

with this your path is only added once in your configuration. otherwise your path is added in your configuration AND in the symfony plugin and will appear in duplicate.
