### ISSUE TITLE
Asset bundling

### ISSUE THREAD

**Issue by Kami1337** [lhapaipai/vite-plugin-symfony#29]
Hey, I've enjoyed using your plugin so far but I'm trying to find a way to organize the built assets into folders.

Here's the vite.config.js file that I'm using.

```
import { defineConfig } from "vite";
import symfonyPlugin from "vite-plugin-symfony";
import react from '@vitejs/plugin-react-swc'

export default defineConfig({
    plugins: [
        react(),
        symfonyPlugin(),
    ],

    build: {
        rollupOptions: {
            input: {
                app: "./assets/react/src/main.tsx",
                style: "./assets/css/style.less",
            },
            output: {
                chunkFileNames: 'assets/js/[name]-[hash].js',
                entryFileNames: 'assets/js/[name]-[hash].js',
                assetFileNames: ({name}) => {
                    if (/\.(gif|jpe?g|png|svg)$/.test(name ?? '')) {
                        return 'assets/images/[name]-[hash][extname]';
                    }

                    if (/\.css$/.test(name ?? '')) {
                        return 'assets/css/[name]-[hash][extname]';
                    }

                    // default value
                    // ref: https://rollupjs.org/guide/en/#outputassetfilenames
                    return 'assets/[name]-[hash][extname]';
                }
            }
        },
        manifest: true,
        outDir: "public_html",
        emptyOutDir: false,
    },
});
```

This part obviously works as the files do get properly bundled in assets/js assets/css and so on but the issue is that twig import does not recognize them.

I've tried prefixing it with folder but it does not help
e.g.

`    {{ vite_entry_script_tags('js/app', { dependency: 'react' }) }}`

I've also seen there's a "builds" configuration in docs 
https://symfony-vite.pentatrion.com/reference/vite-bundle.html

I've created a yaml and setup the different folders but the page doesn't even render with file being active.

Help appreciated,

Thanks

**Comment by lhapaipai** [comment]
Hi @Kami1337, can you add the content of your entrypoints.json (minimalist version if >=100 lines ;-) ) 
2 versions : 
- when vite server is running
- after `vite build`

**Comment by Kami1337** [comment]
Hey, it actually seems to be working fine for dev environment, however on prod it does throw a 404 when trying to load assets.

The path it's bundled on and the path it's attempting to load looks okay though, sorry about the false report.

I guess I just need to update my projects public folder.

Thanks for quick response and your work on this plugin, it's pretty great
