### ISSUE TITLE
Carelessly setting the outDir folder leads to recursive deletion

### ISSUE THREAD

**Issue by Huppys** [lhapaipai/vite-plugin-symfony#31]
### vite-plugin-symfony version

6.0.1

### vite-bundle version

6.1.0

### your OS, node version, Symfony version, PHP version

OS MacOS 13.6, node 18.16.0, n/a, PHP 8.2.12

### Description

I was suddely missing my project, as one might expect, after setting a custom outDir like this:

````
// file: vite.config.ts
export default defineConfig({
    plugins: [
        symfonyPlugin(),
    ],
    build: {
        outDir: "./",
        ....
    }
});
````
I set the value of `outDir` to `./` before switching to another file in IntelliJ. IntelliJ triggered a "oh, I save your vite config, just in case" and the already running vite development server was restarted right away, triggering the recreation of `entrypoints.json` to that very folder. My project was gone.

### How to reproduce

1. In your vite config, e.g. `vite.config.ts`, set `build.outDir`to a directory outside your project root or equal to your project root. 
2. Trigger a restart of the vite development server, via `npm run dev`
3. Expect this particular folder to contain only a file called `entrypoints.json`.

### Possible Solution

A solution could be to make sure the `outDir` is a child folder of the vite project root. If it's not, the process will exit before any damage is done.

**Comment by lhapaipai** [comment]
thanks @Huppys !!
