### ISSUE TITLE
Cannot find module '@hotwired/stimulus'

### ISSUE THREAD

**Issue by darrylhein** [lhapaipai/vite-plugin-symfony#32]
### vite-plugin-symfony version

6.1.0

### vite-bundle version

6.1.0

### your OS, node version, Symfony version, PHP version

Mac OS, node 18, Symfony 6.3, PHP 8.2

### Description

The plugin requires `@hotwired/stimulus` but as I'm not using Stimulus, I don't have that package installed. The resulting error is:

    Cannot find module '@hotwired/stimulus'

I tried adding `stimulus: false` to my Vite config, but it makes no difference as the require statement is not conditional.

I haven't been able to find the exact spot in the source.

### How to reproduce

Upgrade from 6.0 to 6.1. In 6.0 the package isn't required, but in 6.1 it is.

**Comment by lhapaipai** [comment]
hi @darrylhein, oh your totally right, stimulus should be an optional dependency ! It's fixed in version 6.1.1
