### ISSUE TITLE
Add support for FOSJsRoutingBundle

### ISSUE THREAD

**Issue by SkipTheDragon** [lhapaipai/vite-plugin-symfony#42]
### Description

FOSJsRoutingBundle supports Webpack out of the box, but not Vite. I belive it would be a nice addition as Routing is a important part in any application.

I'm willing to contribute on this feature.

### Example

It doesn't look to hard to integrate as seen here: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/webpack/FosRouting.js

**Comment by lhapaipai** [comment]
Nice, any contribution for this feature is welcome !

**Comment by SkipTheDragon** [comment]
Please refer to: https://github.com/lhapaipai/symfony-vite-dev/pull/24 with any feedback/improvements. Thanks.
