### ISSUE TITLE
Dev server URL not respecting origin in the config

### ISSUE THREAD

**Issue by bohanyang** [lhapaipai/vite-plugin-symfony#9]
First of all thanks for writing this!

### Scenario

I've configured NGINX as a reverse proxy. It is responsible for SSL offloading. Like:

```
Client -> HTTPS/WSS -> NGINX -> HTTP/WS -> Vite Dev Server
```

### Problem

The server config in `vite.config.js` is like this:

```js
{
    server: {
        host: '127.0.0.1',
        port: 23456, // local port listened by Vite and proxied by NGINX
        origin: 'https://example.com', // HTTPS & WSS served by NGINX
    }
}
```

However, the URLs in `entrypoints.json` that this plugin generated are still `http://127.0.0.1:23456`.

### Cause

The URL is produced by this block of code. It generates the URL by combining serveral config options but `server.origin` is ignored.

https://github.com/lhapaipai/vite-plugin-symfony/blob/e6269c3fd106d288adbc05a380cf58dcf07eef13/src/index.ts#L67-L86

### Proposal

Origin should be respected if specified.

```ts
function resolveDevServerUrl(
  address: AddressInfo,
  config: ResolvedConfig,
  pluginOptions: Required<PluginOptions>,
): DevServerUrl {
  if (config.server?.origin) {
    return config.server.origin as DevServerUrl
  }
  ...

```

Thanks!

**Comment by lhapaipai** [comment]
this commit should fix your issue, don't forget to use strictPort
```js
{
    server: {
        strictPort: true,
        host: '127.0.0.1',
        port: 23456, // local port listened by Vite and proxied by NGINX
        origin: 'https://example.com', // HTTPS & WSS served by NGINX
    }
}
```
good evening

**Comment by bohanyang** [comment]
Great, thanks!
